In [1]:
from __future__ import division
%matplotlib inline
import numpy as np
from numpy.random import rand
import matplotlib.pyplot as plt

In [169]:
nt = 100000
N = 4
picks = np.random.randint(N, size=(nt, 2))
gens = 2*np.random.randint(2, size=(nt, N, N))-1

In [170]:
def func(picks, gens):
    x = picks[0]
    y = picks[1]
    gens.setflags(write=1)
    gens[x][y] = 5
    return gens

In [171]:
vfunc = np.vectorize(func, signature='(2),(N,N)->(N,N)')

In [172]:
xx = picks[:, 0]
yy = picks[0, :1]

In [173]:
%%time
gens[np.arange(nt), xx, yy] = 5

CPU times: user 2.83 ms, sys: 4.37 ms, total: 7.2 ms
Wall time: 9.36 ms


In [158]:
%%time
vfunc(picks, gens)

CPU times: user 3.11 s, sys: 74.8 ms, total: 3.19 s
Wall time: 3.22 s


array([[[-1, -1, -1, -1],
        [-1,  1,  1,  1],
        [ 1,  1,  5,  5],
        [ 1, -1, -1, -1]],

       [[ 1, -1,  5,  5],
        [-1,  1, -1, -1],
        [-1, -1,  1,  1],
        [-1,  1, -1,  1]],

       [[ 1,  1,  5,  5],
        [-1, -1, -1, -1],
        [ 1,  1, -1, -1],
        [ 1,  1,  1,  1]],

       ...,

       [[ 1, -1, -1,  1],
        [ 5,  1,  5,  1],
        [-1,  1, -1,  1],
        [-1,  1, -1, -1]],

       [[ 1, -1, -1, -1],
        [ 1, -1, -1, -1],
        [ 1,  5,  5, -1],
        [ 1, -1, -1,  1]],

       [[ 1, -1,  1, -1],
        [ 5,  1,  5,  1],
        [ 1,  1,  1,  1],
        [ 1, -1, -1,  1]]])

In [83]:
for 

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [56]:
convolve = np.vectorize(np.convolve, signature='(n),(m)->(k)')
convolve(np.eye(4), [1, 2, 1])

array([[1., 2., 1., 0., 0., 0.],
       [0., 1., 2., 1., 0., 0.],
       [0., 0., 1., 2., 1., 0.],
       [0., 0., 0., 1., 2., 1.]])

In [78]:
test_ar = np.array([np.eye(4), np.eye(4)])
test_vec = np.array([[1, 1, 1, 1], [2, 2, 2, 2]])

In [66]:
A = np.eye(4)
A.dot([1, 1, 1, 1])

array([1., 1., 1., 1.])

In [70]:
np.inner(A, [2, 1, 1, 1]) 

array([2., 1., 1., 1.])

In [73]:
inner_v = np.vectorize(np.inner, signature = '(n,n),(n)->(n)')

In [79]:
inner_v(test_ar, test_vec)

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.]])